# Generated by Django 3.2.16 on 2023-01-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactBook',
            new_name='ContactDetails',
        ),
    ]
