# Generated by Django 3.2.16 on 2023-01-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_rename_contactbook_contactdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
